// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsExports = {
  "aws_project_region": "us-east-1",
  "aws_cognito_identity_pool_id": "us-east-1:226ff871-8126-47ff-8ddf-9874dbce1cc0",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_NnR8nBosN",
  "aws_user_pools_web_client_id": "7a83da26dkeiksgut84at3mmcm",
  "oauth": {
      "domain": "pedra1.auth.us-east-1.amazoncognito.com",
      "scope": [
          "phone",
          "email",
          "openid",
          "profile",
          "aws.cognito.signin.user.admin"
      ],
      "redirectSignIn": "http://localhost:3000/",
      "redirectSignOut": "http://localhost:3000/",
      "responseType": "code"
  },
  "federationTarget": "COGNITO_USER_POOLS"
};

export default awsExports;
